### ISSUE TITLE
Bewerbung FelixFab

### ISSUE THREAD

**Issue by Felix-Fab** [Teidda/Applications#1]
Heyy
Ich würde mich gerne als Software engineer (Andoid) bewerben

Ich bin 16 Jahre alt gehe in die 10. Klasse der Realschule und wohne in Hessen.

Ich programmiere jetzt schon seit dem ich 12 Jahre alt bin. Angefangen habe ich langsam mit Java . Heute kann ich sehr gut Java, SQL, Php und Python. Mit Java habe ich schon Spiele, Programme, Android Apps und Discord Bots programmiert.

Da ich lange in Minecraft Teams und  ich oft immer das gleiche gemacht habe, bin ich fast alle Teams geleavt und suche ein neues und abwechslungsreiches Projekt.

Ich hoffe dir hat die Bewerbung gefallen und bekomme bald eine Rückmeldung 

Gruß FelixFab

**Comment by MauricePascal** [comment]
Danke, wir werden uns bei dir melden

**Comment by Ari24-cb24** [comment]
Ja, werden wir

**Comment by MauricePascal** [comment]
Angenommen
